[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "c-extension"
version = "0.1.0"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: C",
    "Programming Language :: Python :: Implementation :: CPython",
]
